### ISSUE TITLE
The segmentation effect of Cityscapes dataset

### ISSUE THREAD

**Issue by CurryKd7** [twke18/CAST#7]
Hello, I would like to know how many miou metrics can you achieve for fully supervised segmentation of the cityscapes dataset using your CAST method, and how many epochs have you run in total?

**Comment by twke18** [comment]
Hi,

Please check A.3 in the paper for our results on Cityscapes.  For hyper-parameters of training and testing, we follow the default ones in the [segmenter](https://github.com/rstrudel/segmenter/blob/master/segm/scripts/prepare_cityscapes.py) repo.
